version: '1.0.0'

services:
    mysql:
        image: mysql
        restart: always
        environment:            
              MYSQL_DATABASE: 'api_prueba'
              MYSQL_USER: 'andresmz'
              MYSQL_PASSWORD: 'amz12345678'
              MYSQL_ROOT_PASSWORD: 'amz12345'
        ports:
            - '3306:3306'
        expose:
            - '3306'